// Code generated by godddx, DO AVOID EDIT.
package sms

import "github.com/ixugo/goddd/pkg/orm"

// Storer 数据持久化聚合接口
type Storer interface {
	Begin() (orm.Tx, error)
	MediaServer() MediaServerStorer
}

// Core business domain
type Core struct {
	storer Storer
	*NodeManager
}

// NewCore create business domain
func NewCore(store Storer) Core {
	return Core{
		storer: store,

		NodeManager: NewNodeManager(store),
	}
}
