// Code generated by godddx, DO AVOID EDIT.
package recordingcache

import (
	"github.com/gowvp/owl/internal/core/recording"
	"github.com/ixugo/goddd/pkg/conc"
	"github.com/ixugo/goddd/pkg/orm"
)

var _ recording.Storer = (*Cache)(nil)

func NewCache(store recording.Storer, cache conc.Cacher) *Cache {
	return &Cache{
		store:     store,
		recording: cache,
	}
}

type Cache struct {
	store     recording.Storer
	recording conc.Cacher
	txStore   recording.RecordingStorer // WithTx 时设置，正常为 nil
}

// Begin 开启事务
func (c *Cache) Begin() (orm.Tx, error) {
	return c.store.Begin()
}

// Recording 获取 RecordingStorer 实例
func (c *Cache) Recording() recording.RecordingStorer {
	return (*Recording)(c)
}
