// Code generated by godddx, DO AVOID EDIT.
package recordingcache

import (
	"context"
	"fmt"

	"github.com/gowvp/owl/internal/core/recording"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ recording.RecordingStorer = (*Recording)(nil)

type Recording Cache

func (c *Recording) cacheKey(key any) string {
	return fmt.Sprintf("RECORDING:%v", key)
}

// WithTx 返回使用指定事务的 Store 副本（事务内仅失效缓存，读直连 db）
func (c *Recording) WithTx(tx orm.Tx) (recording.RecordingStorer, error) {
	txStore, err := c.store.Recording().WithTx(tx)
	if err != nil {
		return nil, err
	}
	return &Recording{store: c.store, recording: c.recording, txStore: txStore}, nil
}

// List 分页查询（不走缓存）
func (c *Recording) List(ctx context.Context, in *recording.FindRecordingInput) ([]*recording.Recording, int64, error) {
	return c.getStore().List(ctx, in)
}

// GetByID 按主键查询，命中缓存则跳过 db
func (c *Recording) GetByID(ctx context.Context, id int64) (*recording.Recording, error) {
	var model recording.Recording
	model.ID = id
	if model.CacheKey() != "" {
		if err := c.recording.Get(ctx, c.cacheKey(model.CacheKey()), &model); err == nil {
			return &model, nil
		}
	}
	out, err := c.getStore().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	c.recording.SetNX(ctx, c.cacheKey(out.CacheKey()), out)
	return out, nil
}

// Create 创建
func (c *Recording) Create(ctx context.Context, model *recording.Recording) error {
	if err := c.getStore().Create(ctx, model); err != nil {
		return err
	}
	c.recording.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Update 更新
func (c *Recording) Update(ctx context.Context, model *recording.Recording, changeFn func(*recording.Recording) error) error {
	if err := c.getStore().Update(ctx, model, changeFn); err != nil {
		return err
	}
	c.recording.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Delete 删除
func (c *Recording) Delete(ctx context.Context, model *recording.Recording) error {
	if err := c.getStore().Delete(ctx, model); err != nil {
		return err
	}
	c.recording.Del(ctx, c.cacheKey(model.CacheKey()))
	return nil
}

// Count 统计
func (c *Recording) Count(ctx context.Context, in *recording.FindRecordingInput) (int64, error) {
	return c.getStore().Count(ctx, in)
}

// Session 事务组合
func (c *Recording) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return c.store.Recording().Session(ctx, changeFns...)
}

// getStore 事务内使用 txStore，否则使用 db store
func (c *Recording) getStore() recording.RecordingStorer {
	if c.txStore != nil {
		return c.txStore
	}
	return c.store.Recording()
}
