// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"strconv"

	"github.com/gin-gonic/gin"
	"github.com/gowvp/gb28181/internal/conf"
	"github.com/gowvp/gb28181/internal/core/config"
	"github.com/gowvp/gb28181/internal/core/config/store/configdb"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

type ConfigAPI struct {
	configCore config.Core
	conf       *conf.Bootstrap
}

func NewConfigAPI(db *gorm.DB, conf *conf.Bootstrap) ConfigAPI {
	core := config.NewCore(configdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate()))
	return ConfigAPI{configCore: core, conf: conf}
}

func registerConfig(g gin.IRouter, api ConfigAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/configs", handler...)
		// group.GET("", web.WrapH(api.findConfig))
		// group.GET("/:id", web.WrapH(api.getConfig))
		// group.PUT("/:id", web.WrapH(api.editConfig))
		// group.POST("", web.WrapH(api.addConfig))
		// group.DELETE("/:id", web.WrapH(api.delConfig))

		group.GET("/info", web.WrapH(api.getConfigInfo))
		group.PUT("/info/sip", web.WrapH(api.editSIP))
		group.PUT("/info/server", web.WrapH(api.editServerSettings))
	}
}

// >>> config >>>>>>>>>>>>>>>>>>>>

func (a ConfigAPI) findConfig(c *gin.Context, in *config.FindConfigInput) (any, error) {
	items, total, err := a.configCore.FindConfig(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a ConfigAPI) getConfig(c *gin.Context, _ *struct{}) (any, error) {
	configID, _ := strconv.Atoi(c.Param("id"))
	return a.configCore.GetConfig(c.Request.Context(), configID)
}

func (a ConfigAPI) editConfig(c *gin.Context, in *config.EditConfigInput) (any, error) {
	configID, _ := strconv.Atoi(c.Param("id"))
	return a.configCore.EditConfig(c.Request.Context(), in, configID)
}

func (a ConfigAPI) addConfig(c *gin.Context, in *config.AddConfigInput) (any, error) {
	return a.configCore.AddConfig(c.Request.Context(), in)
}

func (a ConfigAPI) delConfig(c *gin.Context, _ *struct{}) (any, error) {
	configID, _ := strconv.Atoi(c.Param("id"))
	return a.configCore.DelConfig(c.Request.Context(), configID)
}

type getConfigInfoOutput struct {
	SIP                conf.SIP `json:"sip"`
	PlayExpireMinutes  int      `json:"play_expire_minutes"`  // 播放链接有效期(分钟)
	EnableSnapshotBlur bool     `json:"enable_snapshot_blur"` // 是否启用快照毛玻璃效果
}

func (a ConfigAPI) getConfigInfo(c *gin.Context, _ *struct{}) (*getConfigInfoOutput, error) {
	return &getConfigInfoOutput{
		SIP:                a.conf.Sip,
		PlayExpireMinutes:  a.conf.Server.PlayExpireMinutes,
		EnableSnapshotBlur: a.conf.Server.EnableSnapshotBlur,
	}, nil
}

func (a ConfigAPI) editSIP(_ *gin.Context, in *conf.SIP) (gin.H, error) {
	if err := copier.Copy(&a.conf.Sip, in); err != nil {
		return nil, reason.ErrServer.SetMsg(err.Error())
	}

	if err := conf.WriteConfig(a.conf, a.conf.ConfigPath); err != nil {
		return nil, reason.ErrServer.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// editServerSettingsInput 服务器设置输入
type editServerSettingsInput struct {
	PlayExpireMinutes  *int  `json:"play_expire_minutes"`  // 播放链接有效期(分钟)
	EnableSnapshotBlur *bool `json:"enable_snapshot_blur"` // 是否启用快照毛玻璃效果
}

// editServerSettings 修改服务器设置
func (a ConfigAPI) editServerSettings(_ *gin.Context, in *editServerSettingsInput) (gin.H, error) {
	if in.PlayExpireMinutes != nil {
		a.conf.Server.PlayExpireMinutes = *in.PlayExpireMinutes
	}
	if in.EnableSnapshotBlur != nil {
		a.conf.Server.EnableSnapshotBlur = *in.EnableSnapshotBlur
	}

	if err := conf.WriteConfig(a.conf, a.conf.ConfigPath); err != nil {
		return nil, reason.ErrServer.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}
