// Code generated by godddx, DO AVOID EDIT.
package configdb

import (
	"context"

	"github.com/gowvp/owl/internal/core/config"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var _ config.ConfigStorer = Config{}

// Config Related business namespaces
type Config DB

// WithTx 返回使用指定事务的 Store 副本
func (d Config) WithTx(tx orm.Tx) (config.ConfigStorer, error) {
	return &Config{db: orm.GormDB(tx)}, nil
}

// List 分页查询
func (d Config) List(ctx context.Context, in *config.FindConfigInput) ([]*config.Config, int64, error) {
	db := d.db.Model(new(config.Config)).WithContext(ctx)
	if in.Type != "" {
		db = db.Where("type = ?", in.Type)
	}
	var total int64
	if err := db.Count(&total).Error; err != nil || total <= 0 {
		return nil, total, err
	}
	var bs []*config.Config
	return bs, total, db.Limit(in.Limit()).Offset(in.Offset()).Find(&bs).Error
}

// GetByID 按主键查询单条
func (d Config) GetByID(ctx context.Context, id string) (*config.Config, error) {
	if id == "" {
		panic("config: GetByID called with empty ID")
	}
	model := config.Config{ID: id}
	if err := d.db.WithContext(ctx).Take(&model).Error; err != nil {
		return nil, err
	}
	return &model, nil
}

// Create 创建
func (d Config) Create(ctx context.Context, model *config.Config) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update 原子更新：SELECT FOR UPDATE + changeFn + Save
func (d Config) Update(ctx context.Context, model *config.Config, changeFn func(*config.Config) error) error {
	if model.ID == "" {
		panic("config: Update called with empty ID")
	}
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Take(model).Error; err != nil {
			return err
		}
		if err := changeFn(model); err != nil {
			return err
		}
		return tx.Save(model).Error
	})
}

// Delete 幂等删除
func (d Config) Delete(ctx context.Context, model *config.Config) error {
	if model.ID == "" {
		panic("config: Delete called with empty ID")
	}
	return d.db.WithContext(ctx).Clauses(clause.Returning{}).Delete(model).Error
}

// FirstOrCreate 首次插入或返回已有记录
func (d Config) FirstOrCreate(model *config.Config) error {
	return d.db.FirstOrCreate(model).Error
}
