// Code generated by godddx, DO AVOID EDIT.
package ipc

import (
	"github.com/gowvp/gb28181/internal/core/port"
	"github.com/ixugo/goddd/domain/uniqueid"
)

// Storer data persistence
type Storer interface {
	Device() DeviceStorer
	Channel() ChannelStorer
}

// Core business domain
type Core struct {
	store     Storer
	uniqueID  uniqueid.Core
	protocols map[string]port.Protocol // 协议映射
}

// NewCore create business domain
func NewCore(store Storer, uni uniqueid.Core, protocols map[string]port.Protocol) Core {
	return Core{
		store:     store,
		uniqueID:  uni,
		protocols: protocols,
	}
}
