// Code generated by godddx, DO AVOID EDIT.
package ipc

import (
	"github.com/ixugo/goddd/domain/uniqueid"
	"github.com/ixugo/goddd/pkg/orm"
)

// Storer data persistence
type Storer interface {
	Begin() (orm.Tx, error)
	Device() DeviceStorer
	Channel() ChannelStorer
}

// CoverManager 快照文件管理接口，Core 内部调用 Remove，外部通过 Cover() 获取完整能力。
type CoverManager interface {
	Write(channelID string, data []byte) error
	ReadPath(channelID string) string
	Read(channelID string) ([]byte, error)
	Remove(channelID string)
}

// Option 用于配置 Core 的可选参数。
type Option func(*Core)

// WithCoverManager 注入快照管理器，通道删除时自动清理快照文件。
func WithCoverManager(cm CoverManager) Option {
	return func(c *Core) { c.coverManager = cm }
}

// Core business domain
type Core struct {
	store        Storer
	uniqueID     uniqueid.Core
	protocols    map[string]Protocoler // 协议映射（Protocol 在同一个包内）
	coverManager CoverManager
}

// NewCore create business domain
func NewCore(store Storer, uni uniqueid.Core, protocols map[string]Protocoler, opts ...Option) Core {
	c := Core{
		store:     store,
		uniqueID:  uni,
		protocols: protocols,
	}
	for _, opt := range opts {
		opt(&c)
	}
	return c
}

func (c Core) GetProtocol(atype string) Protocoler {
	return c.protocols[atype]
}

// Cover 返回快照管理器，外部通过此方法读写快照。
func (c Core) Cover() CoverManager {
	return c.coverManager
}

// getProtocolKeys 获取所有可用的协议类型键名（用于调试）
func (c Core) getProtocolKeys() []string {
	keys := make([]string, 0, len(c.protocols))
	for k := range c.protocols {
		keys = append(keys, k)
	}
	return keys
}
