// Code generated by godddx, DO AVOID EDIT.
package smsdb

import (
	"context"

	"github.com/gowvp/owl/internal/core/sms"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var _ sms.MediaServerStorer = MediaServer{}

// MediaServer Related business namespaces
type MediaServer DB

// WithTx 返回使用指定事务的 Store 副本
func (d MediaServer) WithTx(tx orm.Tx) (sms.MediaServerStorer, error) {
	return &MediaServer{db: orm.GormDB(tx)}, nil
}

// List 分页查询
func (d MediaServer) List(ctx context.Context, in *sms.FindMediaServerInput) ([]*sms.MediaServer, int64, error) {
	db := d.db.Model(new(sms.MediaServer)).WithContext(ctx)
	var total int64
	if err := db.Count(&total).Error; err != nil || total <= 0 {
		return nil, total, err
	}
	var bs []*sms.MediaServer
	return bs, total, db.Limit(in.Limit()).Offset(in.Offset()).Find(&bs).Error
}

// GetByID 按主键查询单条
func (d MediaServer) GetByID(ctx context.Context, id string) (*sms.MediaServer, error) {
	if id == "" {
		panic("sms: GetByID called with empty ID")
	}
	model := sms.MediaServer{ID: id}
	if err := d.db.WithContext(ctx).Take(&model).Error; err != nil {
		return nil, err
	}
	return &model, nil
}

// Create 创建
func (d MediaServer) Create(ctx context.Context, model *sms.MediaServer) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update 原子更新：SELECT FOR UPDATE + changeFn + Save
func (d MediaServer) Update(ctx context.Context, model *sms.MediaServer, changeFn func(*sms.MediaServer) error) error {
	if model.ID == "" {
		panic("sms: Update called with empty ID")
	}
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Take(model).Error; err != nil {
			return err
		}
		if err := changeFn(model); err != nil {
			return err
		}
		return tx.Save(model).Error
	})
}

// Delete 幂等删除
func (d MediaServer) Delete(ctx context.Context, model *sms.MediaServer) error {
	if model.ID == "" {
		panic("sms: Delete called with empty ID")
	}
	return d.db.WithContext(ctx).Clauses(clause.Returning{}).Delete(model).Error
}
